#!/bin/bash
#
# Perform necessary snoopy setup steps prior to installing package.
#

PROGNAME=$(basename $0)
INSTALL_DIR=/opt/snoopy

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

rm -f /etc/snoopy.ini /sbin/snoopy-enable /sbin/snoopy-disable /lib/libsnoopy.so

exit 0
